### ISSUE TITLE
Add internal names to i18n und Migration Content Types

### ISSUE THREAD

**Issue by psolbach** [jungvonmatt/wekit#18]
It would be helpful in the overview to have each entry easily identified by a consistent internal name.

**Comment by bezoerb** [comment]
why need an internal name for i18n objects. They are perfectly identifiable via the translation key.
The same goes for the migration objects. I think adding internal names for these types would only bring some more complexity ;)

**Comment by psolbach** [comment]
More confusing to be exposed to these content types as a client/editor in the first place. If we exclude these content types from cluttering editor views, either via roles or by only guiding client/editors to the Compose view I'm fine with this. Closing the issue.
