### ISSUE TITLE
Remove todos from Storybook introduction page

### ISSUE THREAD

**Issue by peterschewe** [jungvonmatt/wekit#24]
The todos text can be removed in the introduction.md (see [templates/theme-default/content/docs/introduction/_index.md](https://github.com/jungvonmatt/wekit/blob/main/templates/theme-default/content/docs/introduction/_index.md)).

![155138207-23a4d4e4-2c3f-428d-8273-1f59637a1ad9](https://user-images.githubusercontent.com/3438532/176676816-0e1ea81f-4ae8-42d7-8d75-5c32b245acf7.png)

**Comment by peterschewe** [comment]
> hello can I work on this?

Of course! Have fun and let me know if you have any questions.

**Comment by peterschewe** [comment]
Fixed with #29. Thanks to @LewSplenda

**Comment by LewSplenda** [comment]
You're welcome!
