### ISSUE TITLE
TypeError in Storybook server

### ISSUE THREAD

**Issue by peterklostermann** [jungvonmatt/wekit#5]
### What version of WEKit are you using?
v0.6.2 (latest)

### Steps to reproduce 
1. Run `npx @jungvonmatt/create-wekit-app@latest wekit-test-app`
2. Run `npm run storybook`
3. Open http://localhost:6006/

### Current behaviour (bug)
Storybook cannot render stories and displays a TypeError in the console (see below).

### Expected behaviour (correct)
Storybook server starts and stories can be opened.

### Relevant logs and/or media
```
Uncaught TypeError: s.__exportStar is not a function
    at node_modulesVnoptsLibDescriptorsIndexJs (standalone.js:37:1)
    at standalone.js:1:1
    at node_modulesVnoptsLibIndexJs (standalone.js:37:1)
    at standalone.js:1:1
    at srcMainOptionsNormalizerJs (standalone.js:37:1)
    at standalone.js:1:1
    at srcMainOptionsJs (standalone.js:41:1)
    at standalone.js:1:1
    at srcMainCoreJs (standalone.js:41:1)
    at standalone.js:1:1
```

### Other comment
The error is due to **Prettier** version `2.6.0`. The error does not occur with the previous version `2.5.1`.

The `create-wekit-app` script installs devDependencies (see https://github.com/jungvonmatt/wekit/blob/main/packages/create-wekit-app/create-app.ts#L264) in the latest versions. This is likely to cause problems in the future as well. I suggest that we pin the versions and increase them manually.

**Comment by bezoerb** [comment]
Fixed
