### ISSUE TITLE
utils/svg/

### ISSUE THREAD

**Issue by dlemm** [jungvonmatt/wekit#6]
`/core/utils/svg)/parse.html`
Line: 103ff.  seems not working as it should. It only works when every quote is a single quote except for the `viewPort`. 

There is the error 
```
executing "partials/utils/svg/parse.html" at <float $w2>: error calling float: unable to cast "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 371.05 477\"" of type string to float64
```

looks like the regex is broken.

**Comment by dlemm** [comment]
Update: it seems that nor rounded numbers in the viewPort are a problem. Will check if we can transform the input of the calculation to make this work even if the numbers include a decimal point.

**Comment by bezoerb** [comment]
@dlemm: can you post a failing svg?

**Comment by dlemm** [comment]
when it's just `35` it works but with 35.5 it get's the above error (with the stats from the svg)

**Comment by psolbach** [comment]
Just ran into this again. Let's prioritize this task.

**Comment by bezoerb** [comment]
Added a PR with a fix.
Sorry for the late response :)

**Comment by dlemm** [comment]
I think this can be closed then?
