### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by bezoerb** [jungvonmatt/wekit#8]
the current implementation for SEO title isn't flexible enough.

**site.Title** should only be used as fallback for title stored in settings (contentful)

It should be easy in projects to change the seo title schema ($page.title | site.Title)  without the need to overwrite partials/utils/seo/private/get-data.html

**Comment by bezoerb** [comment]
i'm sure there are more things about the current seo implementation that can be addressed :)

**Comment by psolbach** [comment]
Mirrored in public repo.
